version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.0
  windows: circleci/windows@2.2.0

jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "demoDotnet.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
      - run:
          name: "Publish to a subfolder"
          command: dotnet.exe publish --configuration Release --output WebAPiFolder
  verify-install:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - run:
          command: az -v
          name: Verify Azure CLI is installed
  login-to-azure:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - azure-cli/login-with-user:
          alternate-tenant: false
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_TENANT` env var
      - run:
          command: az webapp deployment source show --resource-group laparrilla_portal --name dotnet-core-api
      - run:
          name: "Print Working Directory"
          command: pwd
      - run:
          name: "View all files"
          command: ls
      - run:
          name: "Deploy Web App to Azure"
          command: az webapp deployment source config-local-git --resource-group laparrilla_portal --name dotnet-core-api --app-working-dir C:\Users\circleci\project\WebAPiFolder

workflows:
  example-workflow:
    jobs:
      - build
      - verify-install
      - login-to-azure
